---
- name: configure platform-specific resources
  include: platforms/{{ target_platform }}.yml

- name: configure organizations and their teams
  include: organizations-and-teams.yml

- name: configure all credentails
  include: credentials.yml

- name: configure projects
  include: projects.yml

- name: configure inventories
  include: inventories.yml

- name: configure job templates
  include: job-templates.yml
